// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type ArticleInstance struct {
	Title    string  `json:"title"`
	Subtitle *string `json:"subtitle,omitempty"`
	Body     *string `json:"body,omitempty"`
	AuthorID string  `json:"authorId"`
}

type AuthorInstance struct {
	Name        *string `json:"name,omitempty"`
	Description *string `json:"description,omitempty"`
	Email       string  `json:"email"`
}
