version: '3'

services:
  go-with-rabbitmq:
    build: .
    hostname: go-with-rabbitmq
    container_name: go-with-rabbitmq
    volumes:
      - .:/go/go-with-rabbitmq
    extra_hosts:
      - "host.docker.internal:172.17.0.1"

  rabbitmq:
    image: rabbitmq:3.8.16-management
    container_name: rabbitmq
    hostname: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
      - "15692:15692"
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
      - RABBITMQ_DEFAULT_VHOST=/
